[2023-06-29T11:55:37.066+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-29T08:36:57.167062+00:00 [queued]>
[2023-06-29T11:55:37.084+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-29T08:36:57.167062+00:00 [queued]>
[2023-06-29T11:55:37.086+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-29T11:55:37.116+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): post_to_dynamics_task> on 2023-06-29 08:36:57.167062+00:00
[2023-06-29T11:55:37.128+0000] {standard_task_runner.py:57} INFO - Started process 2343 to run task
[2023-06-29T11:55:37.136+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'order-letter_NER', 'post_to_dynamics_task', 'manual__2023-06-29T08:36:57.167062+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/order-letter-extraction.py', '--cfg-path', '/tmp/tmpbb7h6ol6']
[2023-06-29T11:55:37.141+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask post_to_dynamics_task
[2023-06-29T11:55:37.250+0000] {task_command.py:410} INFO - Running <TaskInstance: order-letter_NER.post_to_dynamics_task manual__2023-06-29T08:36:57.167062+00:00 [running]> on host 2114e0d6603f
[2023-06-29T11:55:37.442+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abin Jilson' AIRFLOW_CTX_DAG_ID='order-letter_NER' AIRFLOW_CTX_TASK_ID='post_to_dynamics_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T08:36:57.167062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-29T08:36:57.167062+00:00'
[2023-06-29T11:55:38.537+0000] {logging_mixin.py:149} INFO - Error: 401 <error xmlns="http://docs.oasis-open.org/odata/ns/metadata"><code>Unauthorized</code><message>The credentials provided are incorrect</message></error>
[2023-06-29T11:55:38.540+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-29T11:55:38.558+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=order-letter_NER, task_id=post_to_dynamics_task, execution_date=20230629T083657, start_date=20230629T115537, end_date=20230629T115538
[2023-06-29T11:55:38.643+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-29T11:55:38.678+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
