[2023-06-28T09:16:03.745+0000] {processor.py:157} INFO - Started process (PID=2398) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:16:03.747+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:16:03.748+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:16:03.748+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:16:03.766+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:16:03.760+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:16:03.767+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:16:03.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.057 seconds
[2023-06-28T09:16:34.236+0000] {processor.py:157} INFO - Started process (PID=2408) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:16:34.237+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:16:34.238+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:16:34.238+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:16:34.254+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:16:34.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:16:34.254+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:16:34.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.049 seconds
[2023-06-28T09:17:04.664+0000] {processor.py:157} INFO - Started process (PID=2417) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:17:04.665+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:17:04.666+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:17:04.666+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:17:04.683+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:17:04.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:17:04.684+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:17:04.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.056 seconds
[2023-06-28T09:17:35.214+0000] {processor.py:157} INFO - Started process (PID=2426) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:17:35.218+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:17:35.221+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:17:35.221+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:17:35.255+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:17:35.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:17:35.259+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:17:35.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.108 seconds
[2023-06-28T09:18:05.844+0000] {processor.py:157} INFO - Started process (PID=2435) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:05.846+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:18:05.847+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:18:05.847+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:05.862+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:18:05.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:18:05.862+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:05.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.050 seconds
[2023-06-28T09:18:06.943+0000] {processor.py:157} INFO - Started process (PID=2436) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:06.944+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:18:06.946+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:18:06.946+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:06.963+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:18:06.961+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:18:06.964+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:06.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.055 seconds
[2023-06-28T09:18:37.439+0000] {processor.py:157} INFO - Started process (PID=2445) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:37.440+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:18:37.442+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:18:37.442+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:37.459+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:18:37.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:18:37.460+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:18:37.487+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.052 seconds
[2023-06-28T09:19:08.021+0000] {processor.py:157} INFO - Started process (PID=2455) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:19:08.023+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:19:08.025+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:19:08.025+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:19:08.041+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:19:08.039+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:19:08.042+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:19:08.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.059 seconds
[2023-06-28T09:19:38.655+0000] {processor.py:157} INFO - Started process (PID=2465) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:19:38.656+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:19:38.658+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:19:38.658+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:19:38.677+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:19:38.675+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:19:38.678+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:19:38.723+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.073 seconds
[2023-06-28T09:20:09.201+0000] {processor.py:157} INFO - Started process (PID=2475) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:20:09.203+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:20:09.204+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:20:09.204+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:20:09.223+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:20:09.222+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:20:09.226+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:20:09.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.062 seconds
[2023-06-28T09:20:39.780+0000] {processor.py:157} INFO - Started process (PID=2485) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:20:39.782+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:20:39.783+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:20:39.783+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:20:39.801+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:20:39.800+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:20:39.802+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:20:39.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.089 seconds
[2023-06-28T09:21:10.411+0000] {processor.py:157} INFO - Started process (PID=2494) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:21:10.412+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:21:10.413+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:21:10.413+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:21:10.428+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:21:10.426+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:21:10.428+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:21:10.460+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.053 seconds
[2023-06-28T09:21:40.903+0000] {processor.py:157} INFO - Started process (PID=2503) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:21:40.905+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:21:40.906+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:21:40.906+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:21:40.924+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:21:40.922+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:21:40.925+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:21:40.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.061 seconds
[2023-06-28T09:22:11.453+0000] {processor.py:157} INFO - Started process (PID=2512) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:22:11.455+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:22:11.457+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:22:11.456+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:22:11.501+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:22:11.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:22:11.503+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:22:11.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.124 seconds
[2023-06-28T09:22:41.942+0000] {processor.py:157} INFO - Started process (PID=2521) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:22:41.943+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:22:41.944+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:22:41.944+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:22:41.959+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:22:41.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:22:41.960+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:22:41.987+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.049 seconds
[2023-06-28T09:23:12.541+0000] {processor.py:157} INFO - Started process (PID=2531) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:23:12.542+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:23:12.543+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:23:12.543+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:23:12.559+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:23:12.557+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:23:12.560+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:23:12.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.051 seconds
[2023-06-28T09:23:31.982+0000] {processor.py:157} INFO - Started process (PID=2540) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:23:31.983+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:23:31.984+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:23:31.984+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:23:31.998+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:23:31.997+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:23:31.999+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:23:32.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.053 seconds
[2023-06-28T09:24:02.585+0000] {processor.py:157} INFO - Started process (PID=2550) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:24:02.586+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:24:02.588+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:24:02.587+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:24:02.605+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:24:02.604+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:24:02.606+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:24:02.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.060 seconds
[2023-06-28T09:24:33.139+0000] {processor.py:157} INFO - Started process (PID=2559) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:24:33.140+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:24:33.141+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:24:33.141+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:24:33.155+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:24:33.154+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:24:33.156+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:24:33.185+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.053 seconds
[2023-06-28T09:25:03.705+0000] {processor.py:157} INFO - Started process (PID=2569) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:25:03.707+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:25:03.708+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:25:03.708+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:25:03.744+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:25:03.742+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:25:03.745+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:25:03.782+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.085 seconds
[2023-06-28T09:25:34.394+0000] {processor.py:157} INFO - Started process (PID=2578) to work on /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:25:34.395+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/order-letter_extraction.py for tasks to queue
[2023-06-28T09:25:34.397+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:25:34.397+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:25:34.417+0000] {logging_mixin.py:149} INFO - [2023-06-28T09:25:34.416+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/order-letter_extraction.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/order-letter_extraction.py", line 5
    from python-files.order-letter-ner.order-letter-ner import read_order_from_mail
               ^
SyntaxError: invalid syntax
[2023-06-28T09:25:34.418+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/order-letter_extraction.py
[2023-06-28T09:25:34.454+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/order-letter_extraction.py took 0.069 seconds
